services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile-flask
    image: myapp-flask
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ./data:/app/data

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    image: myapp-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask
    networks:
      - app-network
    volumes:
      - ./public:/app/public
      - ./nginx/conf:/etc/nginx/conf.d:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf/:/etc/nginx/ssl:ro

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

networks:
  app-network:
    driver: bridge
