# Use the official Nginx image from Docker Hub
FROM nginx:stable-alpine

# Expose ports
EXPOSE 80 443

# Use the "exec" form of CMD to ensure Nginx stays in the foreground
CMD ["nginx", "-g", "daemon off;"]
