version: '3.8'

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile-flask
    image: myapp-flask
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ./data:/app/data

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    image: myapp-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask
    networks:
      - app-network
    volumes:
      - ./public:/app/public
    #   - ./certs:/etc/nginx/ssl
    #   - ./nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  app-network:
    driver: bridge
