# Use the official Nginx image from Docker Hub
FROM nginx:stable-alpine

RUN apk --no-cache add openssl

# Remove the default Nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Copy a new configuration file from the current directory
COPY nginx.conf.example /etc/nginx/nginx.conf

# Copy over SSL certificates
COPY ./certs/cert.pem.example /etc/nginx/ssl/cert.pem
COPY ./certs/cert.key.example /etc/nginx/ssl/cert.key

# Expose ports
EXPOSE 80 443

# Use the "exec" form of CMD to ensure Nginx stays in the foreground
CMD ["nginx", "-g", "daemon off;"]
